<?php

namespace Tests\Property;

use App\Models\Table;
use App\Services\QRCodeService;
use App\Services\TableService;
use Eris\Generators;
use Eris\TestTrait;
use Illuminate\Foundation\Testing\DatabaseTransactions;
use Tests\TestCase;

/**
 * Property 12: QR Code Di-generate Otomatis Saat Meja Dibuat
 *
 * For any table successfully saved to the database, the qr_code column SHALL contain
 * a non-null and non-empty value, automatically generated by the system.
 *
 * Validates: Requirements 4.4
 */
class QrCodeGenerationPropertyTest extends TestCase
{
    use DatabaseTransactions;
    use TestTrait;

    private TableService $tableService;

    protected function setUp(): void
    {
        parent::setUp();

        $this->tableService = app(TableService::class);
    }

    /**
     * After creating a table via TableService::create, qr_code column is non-null and non-empty.
     *
     * **Validates: Requirements 4.4**
     */
    public function testQrCodeIsGeneratedAutomaticallyOnTableCreation(): void
    {
        $this->limitTo(5)->forAll(
            Generators::string()
        )->then(function (string $rawTableNumber) {
            // Sanitize to alphanumeric, max 20 chars
            $tableNumber = substr(preg_replace('/[^a-zA-Z0-9]/', '', $rawTableNumber), 0, 20);

            if (empty($tableNumber)) {
                $tableNumber = 'T' . uniqid();
            }

            $table = $this->tableService->create([
                'table_number' => $tableNumber,
                'name'         => 'Table ' . $tableNumber,
                'capacity'     => 4,
            ]);

            $this->assertNotNull(
                $table->qr_code,
                "qr_code must not be null after table creation (table_number={$tableNumber})"
            );

            $this->assertNotEmpty(
                $table->qr_code,
                "qr_code must not be empty after table creation (table_number={$tableNumber})"
            );

            // Cleanup
            $table->delete();
        });
    }
}
